// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/bff/v1/bffapi.proto

package v1;

public final class BffApiProto {
  private BffApiProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BffApiRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:v1.BffApiRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The query statement
     * </pre>
     *
     * <code>.v1.RequestBody body = 1;</code>
     * @return Whether the body field is set.
     */
    boolean hasBody();
    /**
     * <pre>
     * The query statement
     * </pre>
     *
     * <code>.v1.RequestBody body = 1;</code>
     * @return The body.
     */
    v1.BffApiProto.RequestBody getBody();
    /**
     * <pre>
     * The query statement
     * </pre>
     *
     * <code>.v1.RequestBody body = 1;</code>
     */
    v1.BffApiProto.RequestBodyOrBuilder getBodyOrBuilder();

    /**
     * <pre>
     * The query mask
     * </pre>
     *
     * <code>repeated .google.protobuf.FieldMask field_mask = 2;</code>
     */
    java.util.List<com.google.protobuf.FieldMask> 
        getFieldMaskList();
    /**
     * <pre>
     * The query mask
     * </pre>
     *
     * <code>repeated .google.protobuf.FieldMask field_mask = 2;</code>
     */
    com.google.protobuf.FieldMask getFieldMask(int index);
    /**
     * <pre>
     * The query mask
     * </pre>
     *
     * <code>repeated .google.protobuf.FieldMask field_mask = 2;</code>
     */
    int getFieldMaskCount();
    /**
     * <pre>
     * The query mask
     * </pre>
     *
     * <code>repeated .google.protobuf.FieldMask field_mask = 2;</code>
     */
    java.util.List<? extends com.google.protobuf.FieldMaskOrBuilder> 
        getFieldMaskOrBuilderList();
    /**
     * <pre>
     * The query mask
     * </pre>
     *
     * <code>repeated .google.protobuf.FieldMask field_mask = 2;</code>
     */
    com.google.protobuf.FieldMaskOrBuilder getFieldMaskOrBuilder(
        int index);

    /**
     * <pre>
     * The metadata for user extension.
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */
    int getMetadataCount();
    /**
     * <pre>
     * The metadata for user extension.
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */
    boolean containsMetadata(
        java.lang.String key);
    /**
     * Use {@link #getMetadataMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getMetadata();
    /**
     * <pre>
     * The metadata for user extension.
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getMetadataMap();
    /**
     * <pre>
     * The metadata for user extension.
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */

    java.lang.String getMetadataOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <pre>
     * The metadata for user extension.
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */

    java.lang.String getMetadataOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code v1.BffApiRequest}
   */
  public static final class BffApiRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:v1.BffApiRequest)
      BffApiRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BffApiRequest.newBuilder() to construct.
    private BffApiRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BffApiRequest() {
      fieldMask_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BffApiRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BffApiRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              v1.BffApiProto.RequestBody.Builder subBuilder = null;
              if (body_ != null) {
                subBuilder = body_.toBuilder();
              }
              body_ = input.readMessage(v1.BffApiProto.RequestBody.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(body_);
                body_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                fieldMask_ = new java.util.ArrayList<com.google.protobuf.FieldMask>();
                mutable_bitField0_ |= 0x00000001;
              }
              fieldMask_.add(
                  input.readMessage(com.google.protobuf.FieldMask.parser(), extensionRegistry));
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                metadata_ = com.google.protobuf.MapField.newMapField(
                    MetadataDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              metadata__ = input.readMessage(
                  MetadataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              metadata_.getMutableMap().put(
                  metadata__.getKey(), metadata__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          fieldMask_ = java.util.Collections.unmodifiableList(fieldMask_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return v1.BffApiProto.internal_static_spec_proto_bff_v1_BffApiRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMetadata();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return v1.BffApiProto.internal_static_spec_proto_bff_v1_BffApiRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              v1.BffApiProto.BffApiRequest.class, v1.BffApiProto.BffApiRequest.Builder.class);
    }

    public static final int BODY_FIELD_NUMBER = 1;
    private v1.BffApiProto.RequestBody body_;
    /**
     * <pre>
     * The query statement
     * </pre>
     *
     * <code>.v1.RequestBody body = 1;</code>
     * @return Whether the body field is set.
     */
    @java.lang.Override
    public boolean hasBody() {
      return body_ != null;
    }
    /**
     * <pre>
     * The query statement
     * </pre>
     *
     * <code>.v1.RequestBody body = 1;</code>
     * @return The body.
     */
    @java.lang.Override
    public v1.BffApiProto.RequestBody getBody() {
      return body_ == null ? v1.BffApiProto.RequestBody.getDefaultInstance() : body_;
    }
    /**
     * <pre>
     * The query statement
     * </pre>
     *
     * <code>.v1.RequestBody body = 1;</code>
     */
    @java.lang.Override
    public v1.BffApiProto.RequestBodyOrBuilder getBodyOrBuilder() {
      return getBody();
    }

    public static final int FIELD_MASK_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.FieldMask> fieldMask_;
    /**
     * <pre>
     * The query mask
     * </pre>
     *
     * <code>repeated .google.protobuf.FieldMask field_mask = 2;</code>
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.FieldMask> getFieldMaskList() {
      return fieldMask_;
    }
    /**
     * <pre>
     * The query mask
     * </pre>
     *
     * <code>repeated .google.protobuf.FieldMask field_mask = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.google.protobuf.FieldMaskOrBuilder> 
        getFieldMaskOrBuilderList() {
      return fieldMask_;
    }
    /**
     * <pre>
     * The query mask
     * </pre>
     *
     * <code>repeated .google.protobuf.FieldMask field_mask = 2;</code>
     */
    @java.lang.Override
    public int getFieldMaskCount() {
      return fieldMask_.size();
    }
    /**
     * <pre>
     * The query mask
     * </pre>
     *
     * <code>repeated .google.protobuf.FieldMask field_mask = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.FieldMask getFieldMask(int index) {
      return fieldMask_.get(index);
    }
    /**
     * <pre>
     * The query mask
     * </pre>
     *
     * <code>repeated .google.protobuf.FieldMask field_mask = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.FieldMaskOrBuilder getFieldMaskOrBuilder(
        int index) {
      return fieldMask_.get(index);
    }

    public static final int METADATA_FIELD_NUMBER = 3;
    private static final class MetadataDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  v1.BffApiProto.internal_static_spec_proto_bff_v1_BffApiRequest_MetadataEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> metadata_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMetadata() {
      if (metadata_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MetadataDefaultEntryHolder.defaultEntry);
      }
      return metadata_;
    }

    public int getMetadataCount() {
      return internalGetMetadata().getMap().size();
    }
    /**
     * <pre>
     * The metadata for user extension.
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */

    @java.lang.Override
    public boolean containsMetadata(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetMetadata().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMetadataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMetadata() {
      return getMetadataMap();
    }
    /**
     * <pre>
     * The metadata for user extension.
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getMetadataMap() {
      return internalGetMetadata().getMap();
    }
    /**
     * <pre>
     * The metadata for user extension.
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */
    @java.lang.Override

    public java.lang.String getMetadataOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetadata().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * The metadata for user extension.
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */
    @java.lang.Override

    public java.lang.String getMetadataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetadata().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (body_ != null) {
        output.writeMessage(1, getBody());
      }
      for (int i = 0; i < fieldMask_.size(); i++) {
        output.writeMessage(2, fieldMask_.get(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetMetadata(),
          MetadataDefaultEntryHolder.defaultEntry,
          3);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (body_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBody());
      }
      for (int i = 0; i < fieldMask_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, fieldMask_.get(i));
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetMetadata().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        metadata__ = MetadataDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, metadata__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof v1.BffApiProto.BffApiRequest)) {
        return super.equals(obj);
      }
      v1.BffApiProto.BffApiRequest other = (v1.BffApiProto.BffApiRequest) obj;

      if (hasBody() != other.hasBody()) return false;
      if (hasBody()) {
        if (!getBody()
            .equals(other.getBody())) return false;
      }
      if (!getFieldMaskList()
          .equals(other.getFieldMaskList())) return false;
      if (!internalGetMetadata().equals(
          other.internalGetMetadata())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBody()) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBody().hashCode();
      }
      if (getFieldMaskCount() > 0) {
        hash = (37 * hash) + FIELD_MASK_FIELD_NUMBER;
        hash = (53 * hash) + getFieldMaskList().hashCode();
      }
      if (!internalGetMetadata().getMap().isEmpty()) {
        hash = (37 * hash) + METADATA_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMetadata().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static v1.BffApiProto.BffApiRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static v1.BffApiProto.BffApiRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static v1.BffApiProto.BffApiRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static v1.BffApiProto.BffApiRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static v1.BffApiProto.BffApiRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static v1.BffApiProto.BffApiRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static v1.BffApiProto.BffApiRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static v1.BffApiProto.BffApiRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static v1.BffApiProto.BffApiRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static v1.BffApiProto.BffApiRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static v1.BffApiProto.BffApiRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static v1.BffApiProto.BffApiRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(v1.BffApiProto.BffApiRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code v1.BffApiRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:v1.BffApiRequest)
        v1.BffApiProto.BffApiRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return v1.BffApiProto.internal_static_spec_proto_bff_v1_BffApiRequest_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMetadata();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableMetadata();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return v1.BffApiProto.internal_static_spec_proto_bff_v1_BffApiRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                v1.BffApiProto.BffApiRequest.class, v1.BffApiProto.BffApiRequest.Builder.class);
      }

      // Construct using v1.BffApiProto.BffApiRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFieldMaskFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (bodyBuilder_ == null) {
          body_ = null;
        } else {
          body_ = null;
          bodyBuilder_ = null;
        }
        if (fieldMaskBuilder_ == null) {
          fieldMask_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          fieldMaskBuilder_.clear();
        }
        internalGetMutableMetadata().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return v1.BffApiProto.internal_static_spec_proto_bff_v1_BffApiRequest_descriptor;
      }

      @java.lang.Override
      public v1.BffApiProto.BffApiRequest getDefaultInstanceForType() {
        return v1.BffApiProto.BffApiRequest.getDefaultInstance();
      }

      @java.lang.Override
      public v1.BffApiProto.BffApiRequest build() {
        v1.BffApiProto.BffApiRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public v1.BffApiProto.BffApiRequest buildPartial() {
        v1.BffApiProto.BffApiRequest result = new v1.BffApiProto.BffApiRequest(this);
        int from_bitField0_ = bitField0_;
        if (bodyBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = bodyBuilder_.build();
        }
        if (fieldMaskBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            fieldMask_ = java.util.Collections.unmodifiableList(fieldMask_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.fieldMask_ = fieldMask_;
        } else {
          result.fieldMask_ = fieldMaskBuilder_.build();
        }
        result.metadata_ = internalGetMetadata();
        result.metadata_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof v1.BffApiProto.BffApiRequest) {
          return mergeFrom((v1.BffApiProto.BffApiRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(v1.BffApiProto.BffApiRequest other) {
        if (other == v1.BffApiProto.BffApiRequest.getDefaultInstance()) return this;
        if (other.hasBody()) {
          mergeBody(other.getBody());
        }
        if (fieldMaskBuilder_ == null) {
          if (!other.fieldMask_.isEmpty()) {
            if (fieldMask_.isEmpty()) {
              fieldMask_ = other.fieldMask_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureFieldMaskIsMutable();
              fieldMask_.addAll(other.fieldMask_);
            }
            onChanged();
          }
        } else {
          if (!other.fieldMask_.isEmpty()) {
            if (fieldMaskBuilder_.isEmpty()) {
              fieldMaskBuilder_.dispose();
              fieldMaskBuilder_ = null;
              fieldMask_ = other.fieldMask_;
              bitField0_ = (bitField0_ & ~0x00000001);
              fieldMaskBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getFieldMaskFieldBuilder() : null;
            } else {
              fieldMaskBuilder_.addAllMessages(other.fieldMask_);
            }
          }
        }
        internalGetMutableMetadata().mergeFrom(
            other.internalGetMetadata());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        v1.BffApiProto.BffApiRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (v1.BffApiProto.BffApiRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private v1.BffApiProto.RequestBody body_;
      private com.google.protobuf.SingleFieldBuilderV3<
          v1.BffApiProto.RequestBody, v1.BffApiProto.RequestBody.Builder, v1.BffApiProto.RequestBodyOrBuilder> bodyBuilder_;
      /**
       * <pre>
       * The query statement
       * </pre>
       *
       * <code>.v1.RequestBody body = 1;</code>
       * @return Whether the body field is set.
       */
      public boolean hasBody() {
        return bodyBuilder_ != null || body_ != null;
      }
      /**
       * <pre>
       * The query statement
       * </pre>
       *
       * <code>.v1.RequestBody body = 1;</code>
       * @return The body.
       */
      public v1.BffApiProto.RequestBody getBody() {
        if (bodyBuilder_ == null) {
          return body_ == null ? v1.BffApiProto.RequestBody.getDefaultInstance() : body_;
        } else {
          return bodyBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * The query statement
       * </pre>
       *
       * <code>.v1.RequestBody body = 1;</code>
       */
      public Builder setBody(v1.BffApiProto.RequestBody value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          bodyBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * The query statement
       * </pre>
       *
       * <code>.v1.RequestBody body = 1;</code>
       */
      public Builder setBody(
          v1.BffApiProto.RequestBody.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          bodyBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * The query statement
       * </pre>
       *
       * <code>.v1.RequestBody body = 1;</code>
       */
      public Builder mergeBody(v1.BffApiProto.RequestBody value) {
        if (bodyBuilder_ == null) {
          if (body_ != null) {
            body_ =
              v1.BffApiProto.RequestBody.newBuilder(body_).mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          bodyBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * The query statement
       * </pre>
       *
       * <code>.v1.RequestBody body = 1;</code>
       */
      public Builder clearBody() {
        if (bodyBuilder_ == null) {
          body_ = null;
          onChanged();
        } else {
          body_ = null;
          bodyBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * The query statement
       * </pre>
       *
       * <code>.v1.RequestBody body = 1;</code>
       */
      public v1.BffApiProto.RequestBody.Builder getBodyBuilder() {
        
        onChanged();
        return getBodyFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The query statement
       * </pre>
       *
       * <code>.v1.RequestBody body = 1;</code>
       */
      public v1.BffApiProto.RequestBodyOrBuilder getBodyOrBuilder() {
        if (bodyBuilder_ != null) {
          return bodyBuilder_.getMessageOrBuilder();
        } else {
          return body_ == null ?
              v1.BffApiProto.RequestBody.getDefaultInstance() : body_;
        }
      }
      /**
       * <pre>
       * The query statement
       * </pre>
       *
       * <code>.v1.RequestBody body = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          v1.BffApiProto.RequestBody, v1.BffApiProto.RequestBody.Builder, v1.BffApiProto.RequestBodyOrBuilder>
          getBodyFieldBuilder() {
        if (bodyBuilder_ == null) {
          bodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              v1.BffApiProto.RequestBody, v1.BffApiProto.RequestBody.Builder, v1.BffApiProto.RequestBodyOrBuilder>(
                  getBody(),
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        return bodyBuilder_;
      }

      private java.util.List<com.google.protobuf.FieldMask> fieldMask_ =
        java.util.Collections.emptyList();
      private void ensureFieldMaskIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          fieldMask_ = new java.util.ArrayList<com.google.protobuf.FieldMask>(fieldMask_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder> fieldMaskBuilder_;

      /**
       * <pre>
       * The query mask
       * </pre>
       *
       * <code>repeated .google.protobuf.FieldMask field_mask = 2;</code>
       */
      public java.util.List<com.google.protobuf.FieldMask> getFieldMaskList() {
        if (fieldMaskBuilder_ == null) {
          return java.util.Collections.unmodifiableList(fieldMask_);
        } else {
          return fieldMaskBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * The query mask
       * </pre>
       *
       * <code>repeated .google.protobuf.FieldMask field_mask = 2;</code>
       */
      public int getFieldMaskCount() {
        if (fieldMaskBuilder_ == null) {
          return fieldMask_.size();
        } else {
          return fieldMaskBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * The query mask
       * </pre>
       *
       * <code>repeated .google.protobuf.FieldMask field_mask = 2;</code>
       */
      public com.google.protobuf.FieldMask getFieldMask(int index) {
        if (fieldMaskBuilder_ == null) {
          return fieldMask_.get(index);
        } else {
          return fieldMaskBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * The query mask
       * </pre>
       *
       * <code>repeated .google.protobuf.FieldMask field_mask = 2;</code>
       */
      public Builder setFieldMask(
          int index, com.google.protobuf.FieldMask value) {
        if (fieldMaskBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFieldMaskIsMutable();
          fieldMask_.set(index, value);
          onChanged();
        } else {
          fieldMaskBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * The query mask
       * </pre>
       *
       * <code>repeated .google.protobuf.FieldMask field_mask = 2;</code>
       */
      public Builder setFieldMask(
          int index, com.google.protobuf.FieldMask.Builder builderForValue) {
        if (fieldMaskBuilder_ == null) {
          ensureFieldMaskIsMutable();
          fieldMask_.set(index, builderForValue.build());
          onChanged();
        } else {
          fieldMaskBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * The query mask
       * </pre>
       *
       * <code>repeated .google.protobuf.FieldMask field_mask = 2;</code>
       */
      public Builder addFieldMask(com.google.protobuf.FieldMask value) {
        if (fieldMaskBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFieldMaskIsMutable();
          fieldMask_.add(value);
          onChanged();
        } else {
          fieldMaskBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * The query mask
       * </pre>
       *
       * <code>repeated .google.protobuf.FieldMask field_mask = 2;</code>
       */
      public Builder addFieldMask(
          int index, com.google.protobuf.FieldMask value) {
        if (fieldMaskBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFieldMaskIsMutable();
          fieldMask_.add(index, value);
          onChanged();
        } else {
          fieldMaskBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * The query mask
       * </pre>
       *
       * <code>repeated .google.protobuf.FieldMask field_mask = 2;</code>
       */
      public Builder addFieldMask(
          com.google.protobuf.FieldMask.Builder builderForValue) {
        if (fieldMaskBuilder_ == null) {
          ensureFieldMaskIsMutable();
          fieldMask_.add(builderForValue.build());
          onChanged();
        } else {
          fieldMaskBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * The query mask
       * </pre>
       *
       * <code>repeated .google.protobuf.FieldMask field_mask = 2;</code>
       */
      public Builder addFieldMask(
          int index, com.google.protobuf.FieldMask.Builder builderForValue) {
        if (fieldMaskBuilder_ == null) {
          ensureFieldMaskIsMutable();
          fieldMask_.add(index, builderForValue.build());
          onChanged();
        } else {
          fieldMaskBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * The query mask
       * </pre>
       *
       * <code>repeated .google.protobuf.FieldMask field_mask = 2;</code>
       */
      public Builder addAllFieldMask(
          java.lang.Iterable<? extends com.google.protobuf.FieldMask> values) {
        if (fieldMaskBuilder_ == null) {
          ensureFieldMaskIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, fieldMask_);
          onChanged();
        } else {
          fieldMaskBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * The query mask
       * </pre>
       *
       * <code>repeated .google.protobuf.FieldMask field_mask = 2;</code>
       */
      public Builder clearFieldMask() {
        if (fieldMaskBuilder_ == null) {
          fieldMask_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          fieldMaskBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * The query mask
       * </pre>
       *
       * <code>repeated .google.protobuf.FieldMask field_mask = 2;</code>
       */
      public Builder removeFieldMask(int index) {
        if (fieldMaskBuilder_ == null) {
          ensureFieldMaskIsMutable();
          fieldMask_.remove(index);
          onChanged();
        } else {
          fieldMaskBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * The query mask
       * </pre>
       *
       * <code>repeated .google.protobuf.FieldMask field_mask = 2;</code>
       */
      public com.google.protobuf.FieldMask.Builder getFieldMaskBuilder(
          int index) {
        return getFieldMaskFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * The query mask
       * </pre>
       *
       * <code>repeated .google.protobuf.FieldMask field_mask = 2;</code>
       */
      public com.google.protobuf.FieldMaskOrBuilder getFieldMaskOrBuilder(
          int index) {
        if (fieldMaskBuilder_ == null) {
          return fieldMask_.get(index);  } else {
          return fieldMaskBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * The query mask
       * </pre>
       *
       * <code>repeated .google.protobuf.FieldMask field_mask = 2;</code>
       */
      public java.util.List<? extends com.google.protobuf.FieldMaskOrBuilder> 
           getFieldMaskOrBuilderList() {
        if (fieldMaskBuilder_ != null) {
          return fieldMaskBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(fieldMask_);
        }
      }
      /**
       * <pre>
       * The query mask
       * </pre>
       *
       * <code>repeated .google.protobuf.FieldMask field_mask = 2;</code>
       */
      public com.google.protobuf.FieldMask.Builder addFieldMaskBuilder() {
        return getFieldMaskFieldBuilder().addBuilder(
            com.google.protobuf.FieldMask.getDefaultInstance());
      }
      /**
       * <pre>
       * The query mask
       * </pre>
       *
       * <code>repeated .google.protobuf.FieldMask field_mask = 2;</code>
       */
      public com.google.protobuf.FieldMask.Builder addFieldMaskBuilder(
          int index) {
        return getFieldMaskFieldBuilder().addBuilder(
            index, com.google.protobuf.FieldMask.getDefaultInstance());
      }
      /**
       * <pre>
       * The query mask
       * </pre>
       *
       * <code>repeated .google.protobuf.FieldMask field_mask = 2;</code>
       */
      public java.util.List<com.google.protobuf.FieldMask.Builder> 
           getFieldMaskBuilderList() {
        return getFieldMaskFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder> 
          getFieldMaskFieldBuilder() {
        if (fieldMaskBuilder_ == null) {
          fieldMaskBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder>(
                  fieldMask_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          fieldMask_ = null;
        }
        return fieldMaskBuilder_;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> metadata_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMetadata() {
        if (metadata_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MetadataDefaultEntryHolder.defaultEntry);
        }
        return metadata_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableMetadata() {
        onChanged();;
        if (metadata_ == null) {
          metadata_ = com.google.protobuf.MapField.newMapField(
              MetadataDefaultEntryHolder.defaultEntry);
        }
        if (!metadata_.isMutable()) {
          metadata_ = metadata_.copy();
        }
        return metadata_;
      }

      public int getMetadataCount() {
        return internalGetMetadata().getMap().size();
      }
      /**
       * <pre>
       * The metadata for user extension.
       * </pre>
       *
       * <code>map&lt;string, string&gt; metadata = 3;</code>
       */

      @java.lang.Override
      public boolean containsMetadata(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetMetadata().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMetadataMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getMetadata() {
        return getMetadataMap();
      }
      /**
       * <pre>
       * The metadata for user extension.
       * </pre>
       *
       * <code>map&lt;string, string&gt; metadata = 3;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, java.lang.String> getMetadataMap() {
        return internalGetMetadata().getMap();
      }
      /**
       * <pre>
       * The metadata for user extension.
       * </pre>
       *
       * <code>map&lt;string, string&gt; metadata = 3;</code>
       */
      @java.lang.Override

      public java.lang.String getMetadataOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMetadata().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * The metadata for user extension.
       * </pre>
       *
       * <code>map&lt;string, string&gt; metadata = 3;</code>
       */
      @java.lang.Override

      public java.lang.String getMetadataOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMetadata().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMetadata() {
        internalGetMutableMetadata().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * The metadata for user extension.
       * </pre>
       *
       * <code>map&lt;string, string&gt; metadata = 3;</code>
       */

      public Builder removeMetadata(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableMetadata().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableMetadata() {
        return internalGetMutableMetadata().getMutableMap();
      }
      /**
       * <pre>
       * The metadata for user extension.
       * </pre>
       *
       * <code>map&lt;string, string&gt; metadata = 3;</code>
       */
      public Builder putMetadata(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableMetadata().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       * The metadata for user extension.
       * </pre>
       *
       * <code>map&lt;string, string&gt; metadata = 3;</code>
       */

      public Builder putAllMetadata(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableMetadata().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:v1.BffApiRequest)
    }

    // @@protoc_insertion_point(class_scope:v1.BffApiRequest)
    private static final v1.BffApiProto.BffApiRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new v1.BffApiProto.BffApiRequest();
    }

    public static v1.BffApiProto.BffApiRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BffApiRequest>
        PARSER = new com.google.protobuf.AbstractParser<BffApiRequest>() {
      @java.lang.Override
      public BffApiRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BffApiRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BffApiRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BffApiRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public v1.BffApiProto.BffApiRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RequestBodyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:v1.RequestBody)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The query language
     * </pre>
     *
     * <code>string query = 1;</code>
     * @return The query.
     */
    java.lang.String getQuery();
    /**
     * <pre>
     * The query language
     * </pre>
     *
     * <code>string query = 1;</code>
     * @return The bytes for query.
     */
    com.google.protobuf.ByteString
        getQueryBytes();

    /**
     * <pre>
     * The query variables
     * </pre>
     *
     * <code>string variables = 2;</code>
     * @return The variables.
     */
    java.lang.String getVariables();
    /**
     * <pre>
     * The query variables
     * </pre>
     *
     * <code>string variables = 2;</code>
     * @return The bytes for variables.
     */
    com.google.protobuf.ByteString
        getVariablesBytes();
  }
  /**
   * Protobuf type {@code v1.RequestBody}
   */
  public static final class RequestBody extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:v1.RequestBody)
      RequestBodyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RequestBody.newBuilder() to construct.
    private RequestBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestBody() {
      query_ = "";
      variables_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RequestBody();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RequestBody(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              query_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              variables_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return v1.BffApiProto.internal_static_spec_proto_bff_v1_RequestBody_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return v1.BffApiProto.internal_static_spec_proto_bff_v1_RequestBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              v1.BffApiProto.RequestBody.class, v1.BffApiProto.RequestBody.Builder.class);
    }

    public static final int QUERY_FIELD_NUMBER = 1;
    private volatile java.lang.Object query_;
    /**
     * <pre>
     * The query language
     * </pre>
     *
     * <code>string query = 1;</code>
     * @return The query.
     */
    @java.lang.Override
    public java.lang.String getQuery() {
      java.lang.Object ref = query_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        query_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The query language
     * </pre>
     *
     * <code>string query = 1;</code>
     * @return The bytes for query.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getQueryBytes() {
      java.lang.Object ref = query_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        query_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VARIABLES_FIELD_NUMBER = 2;
    private volatile java.lang.Object variables_;
    /**
     * <pre>
     * The query variables
     * </pre>
     *
     * <code>string variables = 2;</code>
     * @return The variables.
     */
    @java.lang.Override
    public java.lang.String getVariables() {
      java.lang.Object ref = variables_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        variables_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The query variables
     * </pre>
     *
     * <code>string variables = 2;</code>
     * @return The bytes for variables.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVariablesBytes() {
      java.lang.Object ref = variables_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        variables_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(query_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, query_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(variables_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, variables_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(query_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, query_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(variables_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, variables_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof v1.BffApiProto.RequestBody)) {
        return super.equals(obj);
      }
      v1.BffApiProto.RequestBody other = (v1.BffApiProto.RequestBody) obj;

      if (!getQuery()
          .equals(other.getQuery())) return false;
      if (!getVariables()
          .equals(other.getVariables())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + QUERY_FIELD_NUMBER;
      hash = (53 * hash) + getQuery().hashCode();
      hash = (37 * hash) + VARIABLES_FIELD_NUMBER;
      hash = (53 * hash) + getVariables().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static v1.BffApiProto.RequestBody parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static v1.BffApiProto.RequestBody parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static v1.BffApiProto.RequestBody parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static v1.BffApiProto.RequestBody parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static v1.BffApiProto.RequestBody parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static v1.BffApiProto.RequestBody parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static v1.BffApiProto.RequestBody parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static v1.BffApiProto.RequestBody parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static v1.BffApiProto.RequestBody parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static v1.BffApiProto.RequestBody parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static v1.BffApiProto.RequestBody parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static v1.BffApiProto.RequestBody parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(v1.BffApiProto.RequestBody prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code v1.RequestBody}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:v1.RequestBody)
        v1.BffApiProto.RequestBodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return v1.BffApiProto.internal_static_spec_proto_bff_v1_RequestBody_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return v1.BffApiProto.internal_static_spec_proto_bff_v1_RequestBody_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                v1.BffApiProto.RequestBody.class, v1.BffApiProto.RequestBody.Builder.class);
      }

      // Construct using v1.BffApiProto.RequestBody.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        query_ = "";

        variables_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return v1.BffApiProto.internal_static_spec_proto_bff_v1_RequestBody_descriptor;
      }

      @java.lang.Override
      public v1.BffApiProto.RequestBody getDefaultInstanceForType() {
        return v1.BffApiProto.RequestBody.getDefaultInstance();
      }

      @java.lang.Override
      public v1.BffApiProto.RequestBody build() {
        v1.BffApiProto.RequestBody result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public v1.BffApiProto.RequestBody buildPartial() {
        v1.BffApiProto.RequestBody result = new v1.BffApiProto.RequestBody(this);
        result.query_ = query_;
        result.variables_ = variables_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof v1.BffApiProto.RequestBody) {
          return mergeFrom((v1.BffApiProto.RequestBody)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(v1.BffApiProto.RequestBody other) {
        if (other == v1.BffApiProto.RequestBody.getDefaultInstance()) return this;
        if (!other.getQuery().isEmpty()) {
          query_ = other.query_;
          onChanged();
        }
        if (!other.getVariables().isEmpty()) {
          variables_ = other.variables_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        v1.BffApiProto.RequestBody parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (v1.BffApiProto.RequestBody) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object query_ = "";
      /**
       * <pre>
       * The query language
       * </pre>
       *
       * <code>string query = 1;</code>
       * @return The query.
       */
      public java.lang.String getQuery() {
        java.lang.Object ref = query_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          query_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The query language
       * </pre>
       *
       * <code>string query = 1;</code>
       * @return The bytes for query.
       */
      public com.google.protobuf.ByteString
          getQueryBytes() {
        java.lang.Object ref = query_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          query_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The query language
       * </pre>
       *
       * <code>string query = 1;</code>
       * @param value The query to set.
       * @return This builder for chaining.
       */
      public Builder setQuery(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        query_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The query language
       * </pre>
       *
       * <code>string query = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuery() {
        
        query_ = getDefaultInstance().getQuery();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The query language
       * </pre>
       *
       * <code>string query = 1;</code>
       * @param value The bytes for query to set.
       * @return This builder for chaining.
       */
      public Builder setQueryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        query_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object variables_ = "";
      /**
       * <pre>
       * The query variables
       * </pre>
       *
       * <code>string variables = 2;</code>
       * @return The variables.
       */
      public java.lang.String getVariables() {
        java.lang.Object ref = variables_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          variables_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The query variables
       * </pre>
       *
       * <code>string variables = 2;</code>
       * @return The bytes for variables.
       */
      public com.google.protobuf.ByteString
          getVariablesBytes() {
        java.lang.Object ref = variables_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          variables_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The query variables
       * </pre>
       *
       * <code>string variables = 2;</code>
       * @param value The variables to set.
       * @return This builder for chaining.
       */
      public Builder setVariables(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        variables_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The query variables
       * </pre>
       *
       * <code>string variables = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVariables() {
        
        variables_ = getDefaultInstance().getVariables();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The query variables
       * </pre>
       *
       * <code>string variables = 2;</code>
       * @param value The bytes for variables to set.
       * @return This builder for chaining.
       */
      public Builder setVariablesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        variables_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:v1.RequestBody)
    }

    // @@protoc_insertion_point(class_scope:v1.RequestBody)
    private static final v1.BffApiProto.RequestBody DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new v1.BffApiProto.RequestBody();
    }

    public static v1.BffApiProto.RequestBody getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestBody>
        PARSER = new com.google.protobuf.AbstractParser<RequestBody>() {
      @java.lang.Override
      public RequestBody parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestBody(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestBody> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestBody> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public v1.BffApiProto.RequestBody getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BffApiResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:v1.BffApiResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The response data
     * </pre>
     *
     * <code>bytes data = 1;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code v1.BffApiResponse}
   */
  public static final class BffApiResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:v1.BffApiResponse)
      BffApiResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BffApiResponse.newBuilder() to construct.
    private BffApiResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BffApiResponse() {
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BffApiResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BffApiResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return v1.BffApiProto.internal_static_spec_proto_bff_v1_BffApiResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return v1.BffApiProto.internal_static_spec_proto_bff_v1_BffApiResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              v1.BffApiProto.BffApiResponse.class, v1.BffApiProto.BffApiResponse.Builder.class);
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString data_;
    /**
     * <pre>
     * The response data
     * </pre>
     *
     * <code>bytes data = 1;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!data_.isEmpty()) {
        output.writeBytes(1, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof v1.BffApiProto.BffApiResponse)) {
        return super.equals(obj);
      }
      v1.BffApiProto.BffApiResponse other = (v1.BffApiProto.BffApiResponse) obj;

      if (!getData()
          .equals(other.getData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static v1.BffApiProto.BffApiResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static v1.BffApiProto.BffApiResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static v1.BffApiProto.BffApiResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static v1.BffApiProto.BffApiResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static v1.BffApiProto.BffApiResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static v1.BffApiProto.BffApiResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static v1.BffApiProto.BffApiResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static v1.BffApiProto.BffApiResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static v1.BffApiProto.BffApiResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static v1.BffApiProto.BffApiResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static v1.BffApiProto.BffApiResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static v1.BffApiProto.BffApiResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(v1.BffApiProto.BffApiResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code v1.BffApiResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:v1.BffApiResponse)
        v1.BffApiProto.BffApiResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return v1.BffApiProto.internal_static_spec_proto_bff_v1_BffApiResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return v1.BffApiProto.internal_static_spec_proto_bff_v1_BffApiResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                v1.BffApiProto.BffApiResponse.class, v1.BffApiProto.BffApiResponse.Builder.class);
      }

      // Construct using v1.BffApiProto.BffApiResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return v1.BffApiProto.internal_static_spec_proto_bff_v1_BffApiResponse_descriptor;
      }

      @java.lang.Override
      public v1.BffApiProto.BffApiResponse getDefaultInstanceForType() {
        return v1.BffApiProto.BffApiResponse.getDefaultInstance();
      }

      @java.lang.Override
      public v1.BffApiProto.BffApiResponse build() {
        v1.BffApiProto.BffApiResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public v1.BffApiProto.BffApiResponse buildPartial() {
        v1.BffApiProto.BffApiResponse result = new v1.BffApiProto.BffApiResponse(this);
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof v1.BffApiProto.BffApiResponse) {
          return mergeFrom((v1.BffApiProto.BffApiResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(v1.BffApiProto.BffApiResponse other) {
        if (other == v1.BffApiProto.BffApiResponse.getDefaultInstance()) return this;
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        v1.BffApiProto.BffApiResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (v1.BffApiProto.BffApiResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * The response data
       * </pre>
       *
       * <code>bytes data = 1;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <pre>
       * The response data
       * </pre>
       *
       * <code>bytes data = 1;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The response data
       * </pre>
       *
       * <code>bytes data = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:v1.BffApiResponse)
    }

    // @@protoc_insertion_point(class_scope:v1.BffApiResponse)
    private static final v1.BffApiProto.BffApiResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new v1.BffApiProto.BffApiResponse();
    }

    public static v1.BffApiProto.BffApiResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BffApiResponse>
        PARSER = new com.google.protobuf.AbstractParser<BffApiResponse>() {
      @java.lang.Override
      public BffApiResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BffApiResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BffApiResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BffApiResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public v1.BffApiProto.BffApiResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spec_proto_bff_v1_BffApiRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spec_proto_bff_v1_BffApiRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spec_proto_bff_v1_BffApiRequest_MetadataEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spec_proto_bff_v1_BffApiRequest_MetadataEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spec_proto_bff_v1_RequestBody_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spec_proto_bff_v1_RequestBody_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spec_proto_bff_v1_BffApiResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spec_proto_bff_v1_BffApiResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,src/main/resources/proto/bff/v1/bffapi" +
      ".proto\022\021spec.proto.bff.v1\032 google/protob" +
      "uf/field_mask.proto\"\340\001\n\rBffApiRequest\022,\n" +
      "\004body\030\001 \001(\0132\036.v1.RequestB" +
      "ody\022.\n\nfield_mask\030\002 \003(\0132\032.google.protobu" +
      "f.FieldMask\022@\n\010metadata\030\003 \003(\0132..spec.pro" +
      "to.bff.v1.BffApiRequest.MetadataEntry\032/\n" +
      "\rMetadataEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001" +
      "(\t:\0028\001\"/\n\013RequestBody\022\r\n\005query\030\001 \001(\t\022\021\n\t" +
      "variables\030\002 \001(\t\"\036\n\016BffApiResponse\022\014\n\004dat" +
      "a\030\001 \001(\014B \n\021spec.proto.bff.v1B\013BffApiProt" +
      "ob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.FieldMaskProto.getDescriptor(),
        });
    internal_static_spec_proto_bff_v1_BffApiRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_spec_proto_bff_v1_BffApiRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spec_proto_bff_v1_BffApiRequest_descriptor,
        new java.lang.String[] { "Body", "FieldMask", "Metadata", });
    internal_static_spec_proto_bff_v1_BffApiRequest_MetadataEntry_descriptor =
      internal_static_spec_proto_bff_v1_BffApiRequest_descriptor.getNestedTypes().get(0);
    internal_static_spec_proto_bff_v1_BffApiRequest_MetadataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spec_proto_bff_v1_BffApiRequest_MetadataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_spec_proto_bff_v1_RequestBody_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_spec_proto_bff_v1_RequestBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spec_proto_bff_v1_RequestBody_descriptor,
        new java.lang.String[] { "Query", "Variables", });
    internal_static_spec_proto_bff_v1_BffApiResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_spec_proto_bff_v1_BffApiResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spec_proto_bff_v1_BffApiResponse_descriptor,
        new java.lang.String[] { "Data", });
    com.google.protobuf.FieldMaskProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
