name: "Build and Test"
on: [push, pull_request]

jobs:
  build-source:
    name: "Build Source Code"
    runs-on: ubuntu-latest
    env:
      JDK_VER: 11
    steps:
      - name: "Checkout the source code"
        uses: actions/checkout@v2
      - name: "Set up JDK 11"
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: "Build capa-bff-example-dependency"
        run:
          mvn package -pl ./capa-bff-example-dependency
      - name: "docker build and push"
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker build ./capa-bff-example-dependency -t wangjiefourth/capa-example-dependency
          docker push wangjiefourth/capa-example-dependency
      - name: "build capa-bff"
        run: |
          docker run -d -p 8089:8080 --name=cpapa-bff-example-dependency wangjiefourth/capa-example-dependency:latest
          mvn clean && mvn verify
